### ISSUE TITLE
vega-functions 6.1.1 dont work with vega 5.33.1

### ISSUE THREAD

**Issue by mateBe95** [vega/vega#4215]
There is security issue in vega-functions => https://github.com/advisories/GHSA-m9rg-mr6g-75gm
We need to stay at vega 5.33.1 due to CJS project build. However  in package.json trying to override "vega-functions": "6.1.1", cause issues in the UI browser.

installHook.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'domain')
    at Object.scaleGradient [as gradient] (vega-functions.js:389:1)
    at Object.eval (eval at expression (vega-runtime.module.js:88:1), <anonymous>:3:264)
