### ISSUE TITLE
EventStreams lack a detach function, breaking subflow garbage collection

### ISSUE THREAD

**Issue by singhsays** [vega/vega#2753]
I suspect the new subflow GC changes introduced in https://github.com/vega/vega/pull/2652/files#diff-70f2ac46650c107a10f6dc5b7402244aR67 have a bug while cleaning up EventStream nodes.

Here is a stackblitz to reproduce the issue:
https://stackblitz.com/edit/vega-js-eventstream-gc

To Repro:
Click the update data button after the visualization loads, check console for the error.

```
vega.js:131 ERROR TypeError: ctx.nodes[key].detach is not a function
    at Context.detach (vega.js:37380)
    at op.detachSubflow (vega.js:37188)
    at PreFacet.prototype$h.clean (vega.js:8828)
    at vega.js:9881
    at asyncCallback (vega.js:898)
    at View.evaluate (vega.js:5510)
    at async View.prototype$1s.evaluate (vega.js:37777)
```

This can be reproduced with vega@5.13.0 but works fine with vega@5.12.0 (without GC of-course).

Here is a sample spec modified from one of the examples, although this won't work directly in the vega online editor AFAIK since an external data update is needed to repro.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [{"name": "table", "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
   ]}],
  "signals": [{"name": "ydown"}],
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "xscale"},
    {"orient": "left", "scale": "yscale"}
  ],
  "marks": [
    {
      "type": "group",
      "from": {"data": "table"},
      "signals": [
        {
          "name": "ydown",
          "push": "outer",
          "on": [{"events": "@foo:mousedown", "update": "[y(), item().datum]"}]
        },
        {
          "name": "tooltip",
          "value": {},
          "on": [
            {"events": "rect:mouseover", "update": "datum"},
            {"events": "rect:mouseout", "update": "{}"}
          ]
        }
      ],
      "marks": [
        {
          "type": "rect",
          "name": "foo",
          "encode": {
            "enter": {
              "x": {"scale": "xscale", "field": {"parent": "category"}},
              "width": {"scale": "xscale", "band": 1},
              "y": {"scale": "yscale", "field": {"parent": "amount"}},
              "y2": {"scale": "yscale", "value": 0}
            },
            "update": {"fill": {"value": "steelblue"}},
            "hover": {"fill": {"value": "red"}}
          }
        },
        {
          "type": "text",
          "encode": {
            "enter": {
              "align": {"value": "center"},
              "baseline": {"value": "bottom"},
              "fill": {"value": "#333"}
            },
            "update": {
              "x": {
                "scale": "xscale",
                "signal": "tooltip.category",
                "band": 0.5
              },
              "y": {
                "scale": "yscale",
                "signal": "tooltip.amount",
                "offset": -2
              },
              "text": {"signal": "tooltip.amount"},
              "fillOpacity": [
                {"test": "isNaN(tooltip.amount)", "value": 0},
                {"value": 1}
              ]
            }
          }
        }
      ]
    }
  ]
}
```

When a subcontext is detached, all nodes are iterated over and a call made to node.detach.

https://github.com/vega/vega/blob/17bd4f57803bce02ba6e8c290682d05a45f7e717/packages/vega-runtime/src/context.js#L68

This works fine for Operators (and hence Transforms which extend Operators) but not for EventStream nodes which don't extend Operators.

Operators provide the detach method but EventStreams don't

https://github.com/vega/vega/blob/17bd4f57803bce02ba6e8c290682d05a45f7e717/packages/vega-dataflow/src/Operator.js#L194

**Comment by jheer** [comment]
Thank you for catching this oversight. 🤦Will fix soon.
